[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_compiler = "shanghai"
optimizer = true
optimizer_runs = 2000

remappings = [
	"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts"
]